version: '3'
services:
  agents:
    build:
      context: ./agents
    env_file:
      - ./agents/.env
    command: ["python", "./main.py"]
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    networks:
      - default

  backend:
    build:
      context: ./backend
    command: ["python", "./main.py"]
    ports:
      - "80:80"
    depends_on:
      - rabbitmq
    networks:
      - default

  ui:
    build:
      context: ./ui
    env_file:
      - ./ui/.env
    ports:
      - "3000:3000"

  rabbitmq:
    image: rabbitmq:4-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - default
